### ISSUE TITLE
internal values (question/answer representations) are always float64

### ISSUE THREAD

**Issue by guxd** [codekansas/keras-language-modeling#11]
I augment the model to output representations of questions/answers. However, when I call predict to get the question vectors, I found the internal values of model(e.g., question_out, answer_out) are always with dtype='float64'. 
I changed floatX='float32' in both theanorc.txt and  ~/.keras/keras.json, and it doesn't work.
Is there anyway to set the output representations to 'float32'?

**Comment by codekansas** [comment]
Hmm that is interesting. It ran on my GPU alright, which I assume means it was using float32. Maybe check to make sure the datatypes are always `theano.config.floatX`?

**Comment by guxd** [comment]
I checked the code and all dtypes are set to theano.config.floatX. Perhaps it is a bug of Keras..

**Comment by codekansas** [comment]
Is `theanorc.txt` valid? I thought it was supposed to be specified in `$HOME/.theanorc` only

**Comment by codekansas** [comment]
Probably a Theano or Keras issue
