### ISSUE TITLE
Keras 2 compatibility

### ISSUE THREAD

**Issue by zzaibi** [codekansas/keras-language-modeling#39]
I struggled a lot to make the code under keras 2. Could you provide an updated version?

Thanks much!

**Comment by codekansas** [comment]
Hi, I don't plan to update this repo to Keras 2. However, I've rewritten some of the classes in another repository using Keras 2 [here](https://github.com/codekansas/liveqa2017), such as [the recurrent attention wrapper](https://github.com/codekansas/liveqa2017/blob/master/liveqa/nn/utils.py#L10).
