### ISSUE TITLE
How to adapt to Keras 1.03

### ISSUE THREAD

**Issue by wailoktam** [codekansas/keras-language-modeling#9]
I would like to figure out what is going on with the warning about unused output and modify the code.  What do I need to do to get the codes here to run on Keras 1.03? Many thanks in advance.

**Comment by codekansas** [comment]
The unused output warning doesn't actually cause a problem, but if you'd like to get rid of it, it was discussed here https://github.com/codekansas/keras-language-modeling/issues/7
